### ISSUE TITLE
GIF in README

### ISSUE THREAD

**Issue by orta** [dreamengine/DEInfiniteTileMarqueeView#1]
Would be great to see what this does without cloning ( and you can add it to the podspec so people can find out in other applications )

**Comment by dreamengine** [comment]
That's a great idea. Do you know of any easy to use tools to capture a gif from a mac screen?

**Comment by orta** [comment]
QuickTime, & then GIFBrewery for MP4 -> GIF :+1:

**Comment by dreamengine** [comment]
gif is up now. @orta thanks for the info and suggestion!
