### ISSUE TITLE
Cocoapod update

### ISSUE THREAD

**Issue by DimaVartanian** [dreamengine/DEInfiniteTileMarqueeView#3]
Would be great if you could cut a release with the newest changes whenever you get a chance. and just FYI unrelated but noticed the other issue/pull request regarding GIFS. I have found that the quickest/easiest way to make GIFs for this sort of stuff is using LICEcap (http://www.cockos.com/licecap/), made by the winamp guy. That's also how I made the one I submitted in my pull request. Anyways, keep up the good work and thanks again.

**Comment by dreamengine** [comment]
podspec was just merged into Specs. Thanks for the gif suggestion as well!
